// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "UniversityTrainingAdmin",
                            NormalizedName = "UNIVERSITYTRAININGADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "DepartmentHead",
                            NormalizedName = "DEPARTMENTHEAD"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "UniversitySupervisor",
                            NormalizedName = "UNIVERSITYSUPERVISOR"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "4",
                            Name = "InstitutionTrainingOfficer",
                            NormalizedName = "INSTITUTIONTRAININGOFFICER"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "5",
                            Name = "InstitutionSupervisor",
                            NormalizedName = "INSTITUTIONSUPERVISOR"
                        },
                        new
                        {
                            Id = "6",
                            ConcurrencyStamp = "6",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Models.AspNetRoleScope", b =>
                {
                    b.Property<int>("UserRoleScopeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleScopeID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserRoleScopeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UniversityID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("AspNetRoleScopes");
                });

            modelBuilder.Entity("Project.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<string>("InstitutionSupervisorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlacementID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceID");

                    b.HasIndex("InstitutionSupervisorID");

                    b.HasIndex("PlacementID", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("Project.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Project.Models.EmailVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("Project.Models.FieldVisit", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlacementID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversitySupervisorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitID");

                    b.HasIndex("PlacementID");

                    b.HasIndex("UniversitySupervisorID");

                    b.ToTable("FieldVisits");
                });

            modelBuilder.Entity("Project.Models.OpportunityRequestInstitution", b =>
                {
                    b.Property<int>("RequestInstitutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestInstitutionID"));

                    b.Property<int>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestInstitutionID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("RequestID");

                    b.ToTable("OpportunityRequestInstitutions");
                });

            modelBuilder.Entity("Project.Models.OpportunitySkill", b =>
                {
                    b.Property<int>("OpportunitySkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunitySkillID"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("OpportunityID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("OpportunitySkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("OpportunityID", "SkillID")
                        .IsUnique();

                    b.ToTable("OpportunitySkills");
                });

            modelBuilder.Entity("Project.Models.OpportunitySpecialty", b =>
                {
                    b.Property<int>("OpportunitySpecialtyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunitySpecialtyID"));

                    b.Property<int>("OpportunityID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyID")
                        .HasColumnType("int");

                    b.HasKey("OpportunitySpecialtyID");

                    b.HasIndex("SpecialtyID");

                    b.HasIndex("OpportunityID", "SpecialtyID")
                        .IsUnique();

                    b.ToTable("OpportunitySpecialties");
                });

            modelBuilder.Entity("Project.Models.PortfolioItem", b =>
                {
                    b.Property<int>("PortfolioItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortfolioItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortfolioItemID");

                    b.HasIndex("StudentID");

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("Project.Models.RequestSkill", b =>
                {
                    b.Property<int>("RequestSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestSkillID"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("RequestSkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("RequestID", "SkillID")
                        .IsUnique();

                    b.ToTable("RequestSkills");
                });

            modelBuilder.Entity("Project.Models.RequestSpecialty", b =>
                {
                    b.Property<int>("RequestSpecialtyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestSpecialtyID"));

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyID")
                        .HasColumnType("int");

                    b.HasKey("RequestSpecialtyID");

                    b.HasIndex("SpecialtyID");

                    b.HasIndex("RequestID", "SpecialtyID")
                        .IsUnique();

                    b.ToTable("RequestSpecialties");
                });

            modelBuilder.Entity("Project.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SkillID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Project.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyID"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SpecialtyID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Project.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CVPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("GPA")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialtyID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("SpecialtyID");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UniversityID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Project.Models.StudentEvaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluationPdfPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionSupervisorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlacementID")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversitySupervisorID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("InstitutionSupervisorID");

                    b.HasIndex("PlacementID");

                    b.HasIndex("UniversitySupervisorID");

                    b.ToTable("StudentEvaluations");
                });

            modelBuilder.Entity("Project.Models.StudentReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("Content")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlacementID")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversitySupervisorID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReportID");

                    b.HasIndex("PlacementID");

                    b.HasIndex("StudentID");

                    b.HasIndex("UniversitySupervisorID");

                    b.ToTable("StudentReports");
                });

            modelBuilder.Entity("Project.Models.StudentSkill", b =>
                {
                    b.Property<int>("StudentSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSkillID"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("StudentSkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("StudentID", "SkillID")
                        .IsUnique();

                    b.ToTable("StudentSkills");
                });

            modelBuilder.Entity("Project.Models.TrainingApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentDecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentHeadID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DepartmentReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionDecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstitutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InstitutionOfficerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InstitutionReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpportunityID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("StudentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UniversityAdminDecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityAdminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UniversityAdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UniversityAdminReviewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationID");

                    b.HasIndex("DepartmentHeadID");

                    b.HasIndex("InstitutionOfficerID");

                    b.HasIndex("StudentID");

                    b.HasIndex("UniversityAdminID");

                    b.HasIndex("OpportunityID", "StudentID")
                        .IsUnique();

                    b.ToTable("TrainingApplications");
                });

            modelBuilder.Entity("Project.Models.TrainingInstitution", b =>
                {
                    b.Property<int>("InstituationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstituationID"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("InstitutionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstituationID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("TrainingInstitutions");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunity", b =>
                {
                    b.Property<int>("OpportunityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunityID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionOfficerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("RequestID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TrainingTermTermID")
                        .HasColumnType("int");

                    b.HasKey("OpportunityID");

                    b.HasIndex("InstitutionID");

                    b.HasIndex("InstitutionOfficerID");

                    b.HasIndex("RequestID");

                    b.HasIndex("TermID");

                    b.HasIndex("TrainingTermTermID");

                    b.ToTable("TrainingOpportunities");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunityRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentHeadID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("PreferredEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PreferredStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedSeats")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UniversityAdminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UniversityID")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("DepartmentHeadID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("TermID");

                    b.HasIndex("UniversityAdminID");

                    b.HasIndex("UniversityID");

                    b.ToTable("TrainingOpportunityRequests");
                });

            modelBuilder.Entity("Project.Models.TrainingPlacement", b =>
                {
                    b.Property<int>("PlacementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlacementID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstitutionID")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionSupervisorID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OpportunityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TermID")
                        .HasColumnType("int");

                    b.Property<string>("UniversitySupervisorID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlacementID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.HasIndex("InstitutionID");

                    b.HasIndex("InstitutionSupervisorID");

                    b.HasIndex("OpportunityID");

                    b.HasIndex("StudentID");

                    b.HasIndex("TermID");

                    b.HasIndex("UniversitySupervisorID");

                    b.ToTable("TrainingPlacements");
                });

            modelBuilder.Entity("Project.Models.TrainingTerm", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermID"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TermID");

                    b.ToTable("TrainingTerms");
                });

            modelBuilder.Entity("Project.Models.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniversityID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Models.AspNetRoleScope", b =>
                {
                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.TrainingInstitution", "TrainingInstitution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.AspNetUser", "User")
                        .WithOne("RoleScope")
                        .HasForeignKey("Project.Models.AspNetRoleScope", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("TrainingInstitution");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.AttendanceRecord", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "InstitutionSupervisor")
                        .WithMany()
                        .HasForeignKey("InstitutionSupervisorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingPlacement", "TrainingPlacement")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("PlacementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstitutionSupervisor");

                    b.Navigation("TrainingPlacement");
                });

            modelBuilder.Entity("Project.Models.Department", b =>
                {
                    b.HasOne("Project.Models.University", "University")
                        .WithMany("Departments")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Project.Models.EmailVerificationCode", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.FieldVisit", b =>
                {
                    b.HasOne("Project.Models.TrainingPlacement", "TrainingPlacement")
                        .WithMany("FieldVisits")
                        .HasForeignKey("PlacementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversitySupervisor")
                        .WithMany()
                        .HasForeignKey("UniversitySupervisorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingPlacement");

                    b.Navigation("UniversitySupervisor");
                });

            modelBuilder.Entity("Project.Models.OpportunityRequestInstitution", b =>
                {
                    b.HasOne("Project.Models.TrainingInstitution", "TrainingInstitution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingOpportunityRequest", "Request")
                        .WithMany("OpportunityRequests")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("TrainingInstitution");
                });

            modelBuilder.Entity("Project.Models.OpportunitySkill", b =>
                {
                    b.HasOne("Project.Models.TrainingOpportunity", "TrainingOpportunity")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Skill", "Skill")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("TrainingOpportunity");
                });

            modelBuilder.Entity("Project.Models.OpportunitySpecialty", b =>
                {
                    b.HasOne("Project.Models.TrainingOpportunity", "TrainingOpportunity")
                        .WithMany("OpportunitySpecialties")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Specialty", "Specialty")
                        .WithMany("OpportunitySpecialties")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("TrainingOpportunity");
                });

            modelBuilder.Entity("Project.Models.PortfolioItem", b =>
                {
                    b.HasOne("Project.Models.Student", "Student")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Project.Models.RequestSkill", b =>
                {
                    b.HasOne("Project.Models.TrainingOpportunityRequest", "Request")
                        .WithMany("Skills")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Skill", "Skill")
                        .WithMany("RequestSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Project.Models.RequestSpecialty", b =>
                {
                    b.HasOne("Project.Models.TrainingOpportunityRequest", "Request")
                        .WithMany("Specialties")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Specialty", "Specialty")
                        .WithMany("RequestSpecialties")
                        .HasForeignKey("SpecialtyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Project.Models.Specialty", b =>
                {
                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany("Specialties")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project.Models.Student", b =>
                {
                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Project.Models.Specialty", "Specialty")
                        .WithMany("Students")
                        .HasForeignKey("SpecialtyID");

                    b.HasOne("Project.Models.University", "University")
                        .WithMany("Students")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("Project.Models.Student", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Specialty");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.StudentEvaluation", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "InstitutionSupervisor")
                        .WithMany()
                        .HasForeignKey("InstitutionSupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.TrainingPlacement", "TrainingPlacement")
                        .WithMany("StudentEvaluations")
                        .HasForeignKey("PlacementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversitySupervisor")
                        .WithMany()
                        .HasForeignKey("UniversitySupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InstitutionSupervisor");

                    b.Navigation("TrainingPlacement");

                    b.Navigation("UniversitySupervisor");
                });

            modelBuilder.Entity("Project.Models.StudentReport", b =>
                {
                    b.HasOne("Project.Models.TrainingPlacement", "Placement")
                        .WithMany("StudentReports")
                        .HasForeignKey("PlacementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Student", "Student")
                        .WithMany("Reports")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversitySupervisor")
                        .WithMany()
                        .HasForeignKey("UniversitySupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Placement");

                    b.Navigation("Student");

                    b.Navigation("UniversitySupervisor");
                });

            modelBuilder.Entity("Project.Models.StudentSkill", b =>
                {
                    b.HasOne("Project.Models.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.Student", "Student")
                        .WithMany("Skills")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Project.Models.TrainingApplication", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.AspNetUser", "InstitutionOfficer")
                        .WithMany()
                        .HasForeignKey("InstitutionOfficerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.TrainingOpportunity", "TrainingOpportunity")
                        .WithMany()
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversityAdmin")
                        .WithMany()
                        .HasForeignKey("UniversityAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentHead");

                    b.Navigation("InstitutionOfficer");

                    b.Navigation("Student");

                    b.Navigation("TrainingOpportunity");

                    b.Navigation("UniversityAdmin");
                });

            modelBuilder.Entity("Project.Models.TrainingInstitution", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "User")
                        .WithOne("TrainingInstitution")
                        .HasForeignKey("Project.Models.TrainingInstitution", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunity", b =>
                {
                    b.HasOne("Project.Models.TrainingInstitution", "TrainingInstitution")
                        .WithMany("TrainingOpportunities")
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "InstitutionOfficer")
                        .WithMany()
                        .HasForeignKey("InstitutionOfficerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingOpportunityRequest", "Request")
                        .WithMany("Opportunities")
                        .HasForeignKey("RequestID");

                    b.HasOne("Project.Models.TrainingTerm", "TrainingTerm")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingTerm", null)
                        .WithMany("Opportunities")
                        .HasForeignKey("TrainingTermTermID");

                    b.Navigation("InstitutionOfficer");

                    b.Navigation("Request");

                    b.Navigation("TrainingInstitution");

                    b.Navigation("TrainingTerm");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunityRequest", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("Project.Models.TrainingTerm", "TrainingTerm")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversityAdmin")
                        .WithMany()
                        .HasForeignKey("UniversityAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.University", "University")
                        .WithMany("TrainingOpportunityRequests")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DepartmentHead");

                    b.Navigation("TrainingTerm");

                    b.Navigation("University");

                    b.Navigation("UniversityAdmin");
                });

            modelBuilder.Entity("Project.Models.TrainingPlacement", b =>
                {
                    b.HasOne("Project.Models.TrainingApplication", "TrainingApplication")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingInstitution", "TrainingInstitution")
                        .WithMany()
                        .HasForeignKey("InstitutionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "InstitutionSupervisor")
                        .WithMany()
                        .HasForeignKey("InstitutionSupervisorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Models.TrainingOpportunity", "TrainingOpportunity")
                        .WithMany("TrainingPlacement")
                        .HasForeignKey("OpportunityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.TrainingTerm", "TrainingTerm")
                        .WithMany()
                        .HasForeignKey("TermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Models.AspNetUser", "UniversitySupervisor")
                        .WithMany()
                        .HasForeignKey("UniversitySupervisorID");

                    b.Navigation("InstitutionSupervisor");

                    b.Navigation("Student");

                    b.Navigation("TrainingApplication");

                    b.Navigation("TrainingInstitution");

                    b.Navigation("TrainingOpportunity");

                    b.Navigation("TrainingTerm");

                    b.Navigation("UniversitySupervisor");
                });

            modelBuilder.Entity("Project.Models.University", b =>
                {
                    b.HasOne("Project.Models.AspNetUser", "User")
                        .WithOne("University")
                        .HasForeignKey("Project.Models.University", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.AspNetUser", b =>
                {
                    b.Navigation("RoleScope");

                    b.Navigation("Student");

                    b.Navigation("TrainingInstitution");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Project.Models.Department", b =>
                {
                    b.Navigation("Specialties");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Project.Models.Skill", b =>
                {
                    b.Navigation("OpportunitySkills");

                    b.Navigation("RequestSkills");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("Project.Models.Specialty", b =>
                {
                    b.Navigation("OpportunitySpecialties");

                    b.Navigation("RequestSpecialties");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Project.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("PortfolioItems");

                    b.Navigation("Reports");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Project.Models.TrainingInstitution", b =>
                {
                    b.Navigation("TrainingOpportunities");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunity", b =>
                {
                    b.Navigation("OpportunitySkills");

                    b.Navigation("OpportunitySpecialties");

                    b.Navigation("TrainingPlacement");
                });

            modelBuilder.Entity("Project.Models.TrainingOpportunityRequest", b =>
                {
                    b.Navigation("Opportunities");

                    b.Navigation("OpportunityRequests");

                    b.Navigation("Skills");

                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("Project.Models.TrainingPlacement", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("FieldVisits");

                    b.Navigation("StudentEvaluations");

                    b.Navigation("StudentReports");
                });

            modelBuilder.Entity("Project.Models.TrainingTerm", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("Project.Models.University", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Students");

                    b.Navigation("TrainingOpportunityRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
